CREATE TABLE IF NOT EXISTS remedies (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  botanical_name TEXT NOT NULL,
  common_names_json TEXT NOT NULL,
  overview TEXT NOT NULL,
  traditional_uses_json TEXT NOT NULL,
  preparations_json TEXT NOT NULL,
  safety_summary TEXT NOT NULL,
  interaction_flags_json TEXT NOT NULL,
  related_json TEXT NOT NULL,
  tags_json TEXT NOT NULL,
  source_name TEXT NOT NULL,
  source_url TEXT NOT NULL,
  source_status TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_remedies_name ON remedies (name COLLATE NOCASE);

INSERT OR REPLACE INTO remedies
(id, name, botanical_name, common_names_json, overview, traditional_uses_json, preparations_json, safety_summary, interaction_flags_json, related_json, tags_json, source_name, source_url, source_status)
VALUES
('aloe-vera', 'Aloe vera', 'Aloe barbadensis miller', '["Aloe"]', 'Succulent plant indexed for topical skin-soothing traditions and safety-first source review.', '["Topical skin comfort","After-sun care traditions","Digestive laxative tradition for latex"]', '["Topical gel","Juice","Latex safety watch"]', 'Topical gel is the lower-risk public-source context; oral latex requires strong safety review.', '["Pregnancy caution","Kidney and electrolyte caution","Oral latex safety watch"]', '["Calendula","Chamomile","Lavender"]', '["topical","skin","safety watch"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/aloe-vera', 'public_source_indexed'),
('ashwagandha', 'Ashwagandha', 'Withania somnifera', '["Indian ginseng","Winter cherry"]', 'Adaptogen-associated root record for resilience, restoration, and modern safety review.', '["Stress resilience traditions","Restorative sleep context","Vitality traditions"]', '["Capsule","Powder","Tincture"]', 'Needs careful screening for pregnancy, thyroid conditions, autoimmune conditions, and liver-safety reports.', '["Pregnancy caution","Thyroid medication caution","Liver safety watch","Sedative caution"]', '["Asian ginseng","Valerian","Kava"]', '["adaptogen","nervous system","safety watch"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/ashwagandha', 'public_source_indexed'),
('asian-ginseng', 'Asian ginseng', 'Panax ginseng', '["Ginseng","Korean ginseng"]', 'Root remedy associated with vitality and performance traditions, indexed with interaction review.', '["Energy traditions","Resilience traditions","Cognitive performance context"]', '["Capsule","Tea","Extract"]', 'Interaction review is important for diabetes medicines, anticoagulants, stimulants, and sleep sensitivity.', '["Blood sugar medication caution","Anticoagulant caution","Stimulant sensitivity"]', '["Ashwagandha","Green tea","Ginkgo"]', '["adaptogen","energy","root"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/asian-ginseng', 'public_source_indexed'),
('chamomile', 'Chamomile', 'Matricaria recutita / Chamaemelum nobile', '["German chamomile","Roman chamomile"]', 'Flower remedy indexed for sleep, relaxation, and digestive-comfort traditions.', '["Relaxation traditions","Sleep ritual context","Digestive comfort traditions"]', '["Infusion","Tincture","Topical wash"]', 'Asteraceae allergy review matters, especially for people sensitive to ragweed-family plants.', '["Asteraceae allergy caution","Sedative caution","Pregnancy review"]', '["Lavender","Valerian","Peppermint oil"]', '["relaxation","digestive","flower"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/chamomile', 'public_source_indexed'),
('cranberry', 'Cranberry', 'Vaccinium macrocarpon', '["American cranberry"]', 'Berry record associated with urinary-tract wellness traditions and supplement safety review.', '["Urinary wellness context","Food-as-remedy traditions","Antioxidant food context"]', '["Juice","Capsule","Extract"]', 'Review sugar content, kidney-stone history, and anticoagulant concerns before public recommendations.', '["Warfarin caution","Kidney stone history review","Sugar content watch"]', '["Dandelion","Green tea","Garlic"]', '["urinary","berry","food"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/cranberry', 'public_source_indexed'),
('echinacea', 'Echinacea', 'Echinacea purpurea / Echinacea angustifolia', '["Purple coneflower"]', 'Flowering herb indexed for seasonal immune traditions and allergy/autoimmune screening.', '["Seasonal immune traditions","Upper-respiratory wellness context","Short-course tincture traditions"]', '["Tincture","Capsule","Tea"]', 'Allergy and autoimmune-medication review should happen before any public herb guidance.', '["Asteraceae allergy caution","Autoimmune condition review","Immunosuppressant caution"]', '["Elderberry","Goldenseal","Garlic"]', '["immune","seasonal","flower"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/echinacea', 'public_source_indexed'),
('elderberry', 'Elderberry', 'Sambucus nigra', '["Black elder","Elder"]', 'Berry and flower record associated with seasonal wellness traditions.', '["Seasonal immune traditions","Syrup traditions","Flower infusion traditions"]', '["Syrup","Lozenge","Infusion"]', 'Raw or improperly prepared plant parts require safety review; product quality matters.', '["Raw plant safety watch","Autoimmune medication review","Pregnancy review"]', '["Echinacea","Ginger","Green tea"]', '["immune","seasonal","berry"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/elderberry', 'public_source_indexed'),
('garlic', 'Garlic', 'Allium sativum', '["Garlic bulb"]', 'Culinary bulb indexed for cardiovascular and immune traditions with bleeding-risk screening.', '["Cardiovascular food traditions","Immune food traditions","Culinary wellness context"]', '["Food","Capsule","Aged extract"]', 'High-dose supplements require anticoagulant, surgery, and gastrointestinal review.', '["Anticoagulant caution","Surgery caution","Digestive irritation watch"]', '["Ginger","Green tea","Cranberry"]', '["culinary","circulation","immune"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/garlic', 'public_source_indexed'),
('ginger', 'Ginger', 'Zingiber officinale', '["Ginger root"]', 'Rhizome record associated with digestive, nausea, and warming traditions.', '["Digestive comfort traditions","Nausea context","Warming tea traditions"]', '["Tea","Capsule","Food","Tincture"]', 'Review anticoagulant use, gallbladder concerns, pregnancy context, and high-dose supplement use.', '["Anticoagulant caution","Gallbladder review","Pregnancy review at high doses"]', '["Turmeric","Peppermint oil","Garlic"]', '["digestive","rhizome","culinary"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/ginger', 'public_source_indexed'),
('ginkgo', 'Ginkgo', 'Ginkgo biloba', '["Ginkgo leaf"]', 'Leaf extract record associated with cognition and circulation traditions.', '["Cognitive wellness context","Circulation traditions","Aging research interest"]', '["Extract","Capsule","Tea safety watch"]', 'Bleeding-risk and seizure-risk screening are important before public-use guidance.', '["Anticoagulant caution","Seizure medication caution","Surgery caution"]', '["Asian ginseng","Green tea","Garlic"]', '["cognition","circulation","leaf"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/ginkgo', 'public_source_indexed'),
('goldenseal', 'Goldenseal', 'Hydrastis canadensis', '["Orange root"]', 'Root remedy indexed for mucous-membrane and digestive traditions with strong interaction review.', '["Mucous membrane traditions","Digestive bitter traditions","Seasonal wellness formulas"]', '["Tincture","Capsule","Topical wash"]', 'Drug interaction and pregnancy screening are central; conservation and sourcing should also be reviewed.', '["Pregnancy caution","Drug interaction watch","Infant safety caution"]', '["Echinacea","Garlic","Licorice root"]', '["root","immune","safety watch"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/goldenseal', 'public_source_indexed'),
('green-tea', 'Green tea', 'Camellia sinensis', '["Tea leaf"]', 'Tea leaf record associated with antioxidant, alertness, and longevity-adjacent research interest.', '["Daily tea traditions","Alertness context","Polyphenol research context"]', '["Infusion","Powder","Extract safety watch"]', 'Caffeine sensitivity and concentrated extract liver-safety reports need clear review.', '["Caffeine sensitivity","Liver safety watch for extracts","Stimulant caution"]', '["Turmeric","Ginkgo","Asian ginseng"]', '["longevity","tea","polyphenols"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/green-tea', 'public_source_indexed'),
('kava', 'Kava', 'Piper methysticum', '["Kava kava"]', 'Root beverage record associated with relaxation traditions and high-priority safety review.', '["Relaxation traditions","Ceremonial beverage context","Settling formulas"]', '["Traditional beverage","Capsule","Extract"]', 'Liver-safety concerns, sedatives, alcohol, pregnancy, and driving impairment require prominent review.', '["Liver safety watch","Sedative caution","Alcohol caution","Pregnancy caution"]', '["Valerian","Lavender","Ashwagandha"]', '["relaxation","root","high safety watch"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/kava', 'public_source_indexed'),
('lavender', 'Lavender', 'Lavandula angustifolia', '["English lavender"]', 'Aromatic flower record associated with relaxation, sleep ritual, and topical traditions.', '["Aromatherapy traditions","Sleep ritual context","Topical comfort traditions"]', '["Essential oil","Infusion","Topical preparation"]', 'Essential oils need dilution, ingestion caution, and allergy review before public guidance.', '["Topical allergy watch","Essential oil ingestion caution","Sedative caution"]', '["Chamomile","Valerian","Kava"]', '["aromatic","relaxation","flower"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/lavender', 'public_source_indexed'),
('licorice-root', 'Licorice root', 'Glycyrrhiza glabra', '["Licorice"]', 'Root record associated with throat, digestive, and formula-harmonizing traditions.', '["Throat comfort traditions","Digestive traditions","Formula support traditions"]', '["Tea","Tincture","Capsule","DGL product"]', 'Blood pressure, potassium, kidney, heart, pregnancy, and medication interactions require strong screening.', '["Blood pressure caution","Potassium depletion watch","Heart and kidney condition review","Pregnancy caution"]', '["Goldenseal","Ginger","Milk thistle"]', '["root","digestive","high safety watch"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/licorice-root', 'public_source_indexed'),
('milk-thistle', 'Milk thistle', 'Silybum marianum', '["Silymarin"]', 'Seed extract record associated with liver-support traditions and supplement research.', '["Liver-support traditions","Digestive bitter context","Supplement research context"]', '["Capsule","Extract","Tincture"]', 'Review diabetes medicines, allergy sensitivity, and product-quality variability.', '["Diabetes medication caution","Asteraceae allergy caution","Product quality watch"]', '["Turmeric","Dandelion","Licorice root"]', '["liver","seed","extract"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/milk-thistle', 'public_source_indexed'),
('peppermint-oil', 'Peppermint oil', 'Mentha x piperita', '["Peppermint"]', 'Aromatic leaf oil record associated with digestive-comfort traditions and formulation safety.', '["Digestive comfort traditions","Aromatic cooling context","Topical comfort traditions"]', '["Enteric-coated capsule","Infusion","Diluted topical oil"]', 'Reflux, gallbladder conditions, children, and essential-oil dilution need careful review.', '["Reflux caution","Gallbladder review","Child safety watch","Essential oil dilution"]', '["Ginger","Chamomile","Lavender"]', '["digestive","aromatic","leaf"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/peppermint-oil', 'public_source_indexed'),
('saw-palmetto', 'Saw palmetto', 'Serenoa repens', '["Serenoa"]', 'Berry extract record associated with urinary and prostate-wellness research contexts.', '["Urinary wellness context","Prostate wellness research context","Berry extract traditions"]', '["Capsule","Extract","Softgel"]', 'Review anticoagulants, surgery, hormone-sensitive contexts, and reproductive-health claims.', '["Anticoagulant caution","Surgery caution","Hormone medication review"]', '["Cranberry","Green tea","Ginkgo"]', '["urinary","berry","safety review"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/saw-palmetto', 'public_source_indexed'),
('st-johns-wort', 'St. John''s wort', 'Hypericum perforatum', '["Hypericum"]', 'Flowering herb indexed as a high-interaction record for mood-related traditional use.', '["Mood traditions","Nerve-support traditions","Topical infused-oil traditions"]', '["Capsule","Tea","Tincture","Infused oil"]', 'Major drug-interaction screening is mandatory; this record should stay safety-led in public UI.', '["Antidepressant interaction","Contraceptive interaction","Transplant medication interaction","HIV medication interaction","Photosensitivity watch"]', '["Kava","Valerian","Lavender"]', '["mood","high interaction watch","flower"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/st-johns-wort', 'public_source_indexed'),
('turmeric', 'Turmeric', 'Curcuma longa', '["Curcumin"]', 'Rhizome record associated with culinary wellness, inflammatory-pathway research, and supplement safety.', '["Culinary wellness traditions","Joint comfort context","Inflammation research context"]', '["Food","Powder","Capsule","Extract"]', 'High-dose extracts need review for anticoagulants, gallbladder conditions, pregnancy context, and liver reports.', '["Anticoagulant caution","Gallbladder review","Liver safety watch for high-dose extracts","Pregnancy review"]', '["Ginger","Green tea","Milk thistle"]', '["culinary","rhizome","longevity"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/turmeric', 'public_source_indexed'),
('valerian', 'Valerian', 'Valeriana officinalis', '["Valerian root"]', 'Root remedy associated with sleep and evening relaxation traditions.', '["Sleep traditions","Settling traditions","Evening tea or capsule context"]', '["Capsule","Tincture","Infusion"]', 'Sedatives, alcohol, driving, pregnancy, and next-day drowsiness should be reviewed.', '["Sedative caution","Alcohol caution","Driving caution","Pregnancy review"]', '["Chamomile","Lavender","Kava"]', '["sleep","relaxation","root"]', 'NCCIH herb fact sheet', 'https://www.nccih.nih.gov/health/valerian', 'public_source_indexed');
